Dbconnect
ComplexHex/Scrapernews pull request #1
Opened 2024-01-04 08:32 UTC by ComplexHex

2024-01-04 08:54 UTC, efserg requested changes

2024-01-04 08:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/conroller/UserController.java
> +    UserRepository userRepository;
Сделай UserService (интерфейс + имплементация), туда этот репозиторий, здесь инжектишь сервис. Вся логика обработки и взаимодействия с БД - в сервисе. Методы в сервисе должны быть транзакционными

2024-01-04 08:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/conroller/UserController.java
> +    @Autowired
Не используем внедрение зависимостей через поля класса, используем внедрение через конструктор. Надо классом - аннотация lombok `@RequiredArgsConstructor`, поля класса (сервисы) - `private final`

2024-01-04 08:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/conroller/UserController.java
> +@RequestMapping("/api")
Может лучше `/user`?
api можно потом поставить в конфиге спринга

2024-01-04 08:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/conroller/UserController.java
> +    @GetMapping("/users")
лучше в единственном числе `/user`

2024-01-04 08:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/conroller/UserController.java
> +    public ResponseEntity<User> getTutorialById(@PathVariable("id") long id) {
Почему такое странное название метода?

2024-01-04 08:54 UTC, efserg commented on src/main/resources/db/changelog/v1.0/changelog.xml
> +        <createTable tableName="user">
постгря не ругается на такое имя таблицы?

2024-01-04 08:54 UTC, efserg commented on src/main/resources/db/changelog/v1.0/changelog.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Имя файла должно состоять из версии (можно использовать текущую дату, только упорядоченную, т.е. сначала год, месяц, день, часы, минуты и т.д.) и краткого описания того, что делается в этом файле, например: `20240104114317__create-user-table.xml`.

2024-01-04 08:54 UTC, efserg commented on build.gradle
>      testImplementation 'org.springframework.boot:spring-boot-starter-test'
Добавь еще зависимость на mapstruct: https://javarush.com/groups/posts/3698-chto-takoe-mapstruct-i-kak-praviljhno-nastroitjh-ego-dlja-moduljhnogo-testirovanija-v-springboo и https://mapstruct.org/
Твои контроллеры не должны возвращать сущности БД, а должны возвращать dto, которые содержать только необходимые поля. Для этого используются мапперы. Когда ты вынесешь всю логику из контроллера в сервис, то сервис (посредством маппера) как раз и должен превратить БД сущность в дто, которую он и вернет в контроллер.

2024-01-04 08:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/model/User.java
> +@Table(name = "user", schema = "public")
схему отсюда лучше убрать

2024-01-09 05:54 UTC, efserg requested changes

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/entity/User.java
> +@Table(name = "user", schema = "public")
Думаю, отсюда схему лучше убрать

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/mapper/UserMapper.java
> +    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);
Непонятно, зачем тут нужен этот инстанс. Спринг зарегистрирует этот маппер как бин, и дальше мы его можем просто заинжектить

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/service/UserServiceImpl.java
> +    public UserServiceImpl(UserRepository userRepository, UserMapper userMapper) {
Вместо конструктора сделай аннотацию `@RequiredArgsConstructor`, маппер тоже должен быть финальным полем класса

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/service/UserServiceImpl.java
> +    @Transactional(readOnly = true)
Эту аннотацию помести над классом (и именно с `readOnly = true`, тогда все методы класса будут транзакционными и транзакции будут только для чтения. Если потребуется другое поведение (изменение или создание сущности) - тогда уже аннотируй сам метод

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/service/UserServiceImpl.java
> +        User user = userRepository.findById(id).orElse(null);
Бросай исключение, если сущность не найдена: `orElseThrow`.

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/service/UserServiceImpl.java
> +        return UserMapper.INSTANCE.userToUserDTO(user);
Используй поле класса, спринг нормально инжектит mapstruct мапперы

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/service/UserServiceImpl.java
> +    public void save(User user) {
Строго говоря, сервис должен принимать dto и маппить его в ДБ сущность

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/service/UserServiceImpl.java
> +        userRepository.save(user);
Непонятно, этот метод изменяет пользователя или создает нового?

2024-01-09 05:54 UTC, efserg commented on src/main/java/ru/complexhex/scrapernews/conroller/UserController.java
> +}
Добавь ендпоинты для создания, изменения и удаления пользователя. Соответствующие методы должны быть реализованы в сервисе

2024-01-10 03:55 UTC, ComplexHex commented on src/main/java/ru/complexhex/scrapernews/entity/User.java
> +@Table(name = "user", schema = "public")
убираю, прекращается с ошибкой ERROR 17496 --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: column u1_0.id does not exist

2024-01-10 14:01 UTC, efserg approved these changes

2024-01-10 17:07 UTC, merged